import logging

from slime.utils.mask_utils import MultiTurnLossMaskGenerator
from slime.utils.processing_utils import load_processor, load_tokenizer

__all__ = ["generate_rollout"]

logger = logging.getLogger(__name__)


TOKENIZER = None
PROCESSOR = None
MASK_GENERATOR = None
SAMPLE_PRINTED = False
TRUNCATION_WARNING_PRINTED = False


def generate_rollout(args, rollout_id, data_buffer, evaluation=False):
    """An example to implement the generate_rollout function for an rule based rm rollout generation.

    Args:
        args: the whole args
        rollout_id: int, the id of the rollout, used for deterministic data generation
        data_buffer: the data buffer to store the generated samples
        evaluation: bool, whether the rollout is for evaluation or not

    Returns:
        list[Sample]: a list of samples generated by the rollout
    """
    assert not evaluation
    assert args.rollout_global_dataset

    global TOKENIZER, PROCESSOR, MASK_GENERATOR, SAMPLE_PRINTED, TRUNCATION_WARNING_PRINTED
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)

    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)

    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(TOKENIZER, tokenizer_type=args.loss_mask_type)

    max_context_len = getattr(args, "rollout_max_context_len", None)

    samples = data_buffer.get_samples(args.rollout_batch_size)

    for i, sample in enumerate(samples):
        (sample,) = sample
        messages = sample.prompt
        tools = sample.metadata.get("tools", None)

        token_ids, loss_mask = MASK_GENERATOR.get_loss_mask(messages, tools=tools)
         # Truncate if exceeds max_context_len
        if max_context_len is not None and len(token_ids) > max_context_len:
            if not TRUNCATION_WARNING_PRINTED:
                logger.warning(
                    f"sft_rollout: Truncating sample from {len(token_ids)} to {max_context_len} tokens. "
                    f"This warning will only be printed once."
                )
                TRUNCATION_WARNING_PRINTED = True
            token_ids = token_ids[:max_context_len]
            loss_mask = loss_mask[:max_context_len]
        if len(token_ids) != len(loss_mask):
            raise ValueError(
                f"SFT rollout produced mismatched token_ids/loss_mask lengths: {len(token_ids)=}, {len(loss_mask)=}"
            )

        response_length = MASK_GENERATOR.get_response_lengths([loss_mask])[0]

        # After truncation, response may be completely cut off (response_length=0).
        # Assign at least 1 so the sample is still valid; loss_mask will be all-zero
        # meaning no gradient contribution from this sample.
        if response_length == 0:
            response_length = 1
            loss_mask_tail = [0]
        else:
            loss_mask_tail = loss_mask[-response_length:]

        sample.tokens = token_ids
        sample.response_length = response_length
        sample.reward = 0
        sample.loss_mask = loss_mask_tail

        if i == 0 and not SAMPLE_PRINTED:
            # Log token-level loss mask visualization for the first sample
            logger.info("=" * 80)
            logger.info("sft_rollout: FIRST SAMPLE LOSS MASK VISUALIZATION")
            logger.info(f"  total tokens: {len(token_ids)}, response_length: {response_length}")
            logger.info(f"  tokens with loss=1: {sum(loss_mask)}, tokens with loss=0: {len(loss_mask) - sum(loss_mask)}")
            logger.info("-" * 80)

            # Show tokens colored by loss mask: [LOSS] for mask=1, [SKIP] for mask=0
            # Group consecutive tokens with the same mask value for readability
            current_mask = loss_mask[0]
            current_tokens = [token_ids[0]]
            for idx in range(1, len(token_ids)):
                if loss_mask[idx] == current_mask:
                    current_tokens.append(token_ids[idx])
                else:
                    tag = "LOSS" if current_mask == 1 else "SKIP"
                    decoded = TOKENIZER.decode(current_tokens, skip_special_tokens=False)
                    # Truncate very long segments for readability
                    if len(decoded) > 500:
                        decoded = decoded[:250] + " ... " + decoded[-250:]
                    logger.info(f"  [{tag}] ({len(current_tokens)} tokens): {repr(decoded)}")
                    current_mask = loss_mask[idx]
                    current_tokens = [token_ids[idx]]
            # Last segment
            tag = "LOSS" if current_mask == 1 else "SKIP"
            decoded = TOKENIZER.decode(current_tokens, skip_special_tokens=False)
            if len(decoded) > 500:
                decoded = decoded[:250] + " ... " + decoded[-250:]
            logger.info(f"  [{tag}] ({len(current_tokens)} tokens): {repr(decoded)}")
            logger.info("=" * 80)
            SAMPLE_PRINTED = True

    return samples
